# Template of the script, which applies the downloaded update after Terminals exits and shows its progress.
# Generated by UpdateProgressScript, the placeholders (names between double underscores) are replaced by PowerShell literals.
# Keep the syntax compatible with PowerShell 2.0 (Windows 7) and the file ASCII only.
$ErrorActionPreference = 'Stop'

$terminalsProcessId = __PROCESS_ID__
$updateMode = __MODE__
$sourceDirectory = __SOURCE_DIRECTORY__
$targetDirectory = __TARGET_DIRECTORY__
$preservedFiles = __PRESERVED_FILES__
$msiArguments = __MSI_ARGUMENTS__
$terminalsExe = __TERMINALS_EXE__
$logFile = __LOG_FILE__
$fallbackScript = __FALLBACK_SCRIPT__

$textTitle = __TEXT_TITLE__
$textHeader = __TEXT_HEADER__
$textWaiting = __TEXT_WAITING__
$textCopying = __TEXT_COPYING__
$textInstalling = __TEXT_INSTALLING__
$textStarting = __TEXT_STARTING__
$textCopyFailed = __TEXT_COPY_FAILED__
$textInstallFailed = __TEXT_INSTALL_FAILED__

$script:form = $null
$script:statusLabel = $null
$script:progressBar = $null
$script:percentLabel = $null
$script:finished = $false

function Write-UpdateLog([string]$message)
{
    try
    {
        $line = (Get-Date -Format 'yyyy-MM-dd HH:mm:ss') + ' ' + $message + "`r`n"
        [System.IO.File]::AppendAllText($logFile, $line, [System.Text.Encoding]::UTF8)
    }
    catch { }
}

function Show-ProgressWindow
{
    try
    {
        Add-Type -AssemblyName System.Windows.Forms
        Add-Type -AssemblyName System.Drawing
        [System.Windows.Forms.Application]::EnableVisualStyles()

        $font = [System.Drawing.SystemFonts]::MessageBoxFont
        $form = New-Object System.Windows.Forms.Form
        $form.Text = $textTitle
        $form.Font = $font
        $form.FormBorderStyle = [System.Windows.Forms.FormBorderStyle]::FixedDialog
        $form.ControlBox = $false
        $form.StartPosition = [System.Windows.Forms.FormStartPosition]::CenterScreen
        $form.ShowInTaskbar = $true
        $form.BackColor = [System.Drawing.SystemColors]::Window
        $form.ClientSize = New-Object System.Drawing.Size(440, 104)
        try { $form.Icon = [System.Drawing.Icon]::ExtractAssociatedIcon($terminalsExe) } catch { }
        $form.add_FormClosing({ param($sender, $e) if (-not $script:finished) { $e.Cancel = $true } })

        $headerLabel = New-Object System.Windows.Forms.Label
        $headerLabel.Text = $textHeader
        $headerLabel.AutoEllipsis = $true
        $headerLabel.Font = New-Object System.Drawing.Font($font.FontFamily, 11, [System.Drawing.FontStyle]::Bold)
        $headerLabel.Location = New-Object System.Drawing.Point(18, 14)
        $headerLabel.Size = New-Object System.Drawing.Size(404, 24)

        $statusLabel = New-Object System.Windows.Forms.Label
        $statusLabel.AutoEllipsis = $true
        $statusLabel.ForeColor = [System.Drawing.SystemColors]::GrayText
        $statusLabel.Location = New-Object System.Drawing.Point(19, 42)
        $statusLabel.Size = New-Object System.Drawing.Size(404, 18)

        $progressBar = New-Object System.Windows.Forms.ProgressBar
        $progressBar.Location = New-Object System.Drawing.Point(20, 68)
        $progressBar.Size = New-Object System.Drawing.Size(356, 18)

        $percentLabel = New-Object System.Windows.Forms.Label
        $percentLabel.TextAlign = [System.Drawing.ContentAlignment]::MiddleRight
        $percentLabel.Location = New-Object System.Drawing.Point(378, 68)
        $percentLabel.Size = New-Object System.Drawing.Size(44, 18)

        $form.Controls.Add($headerLabel)
        $form.Controls.Add($statusLabel)
        $form.Controls.Add($progressBar)
        $form.Controls.Add($percentLabel)
        $form.Show()
        [System.Windows.Forms.Application]::DoEvents()

        $script:form = $form
        $script:statusLabel = $statusLabel
        $script:progressBar = $progressBar
        $script:percentLabel = $percentLabel
    }
    catch
    {
        # the update has to continue also without the window, e.g. in constrained language mode
        Write-UpdateLog ('Progress window is not available: ' + $_.Exception.Message)
        $script:form = $null
    }
}

function Close-ProgressWindow
{
    $script:finished = $true
    if ($script:form -eq $null) { return }

    try
    {
        $script:form.Close()
        $script:form.Dispose()
    }
    catch { }
    $script:form = $null
}

# Negative percent shows running progress without known end.
function Set-UpdateProgress([string]$status, [int]$percent)
{
    if ($script:form -eq $null) { return }

    try
    {
        if ($status) { $script:statusLabel.Text = $status }

        if ($percent -lt 0)
        {
            $script:progressBar.Style = [System.Windows.Forms.ProgressBarStyle]::Marquee
            $script:percentLabel.Text = ''
        }
        else
        {
            $percent = [Math]::Min(100, $percent)
            $script:progressBar.Style = [System.Windows.Forms.ProgressBarStyle]::Continuous
            $script:progressBar.Value = $percent
            $script:percentLabel.Text = [string]$percent + ' %'
        }

        [System.Windows.Forms.Application]::DoEvents()
    }
    catch { }
}

# Waits while keeping the progress window responsive.
function Wait-Responsive([int]$milliseconds)
{
    $until = (Get-Date).AddMilliseconds($milliseconds)
    do
    {
        if ($script:form -ne $null) { [System.Windows.Forms.Application]::DoEvents() }
        Start-Sleep -Milliseconds 50
    }
    while ((Get-Date) -lt $until)
}

function Show-UpdateFailure([string]$message)
{
    Write-UpdateLog $message
    try
    {
        Add-Type -AssemblyName System.Windows.Forms
        [void][System.Windows.Forms.MessageBox]::Show($script:form, $message, $textTitle,
            [System.Windows.Forms.MessageBoxButtons]::OK, [System.Windows.Forms.MessageBoxIcon]::Warning)
    }
    catch { }
}

# Waits max. 10 minutes for the application to exit, the user may cancel the close.
function Wait-TerminalsExit
{
    $deadline = (Get-Date).AddMinutes(10)
    while ($true)
    {
        $process = Get-Process -Id $terminalsProcessId -ErrorAction SilentlyContinue
        if ($process -eq $null) { return $true }
        if ((Get-Date) -gt $deadline) { return $false }
        Wait-Responsive 200
    }
}

function Copy-UpdateFile([string]$source, [string]$target)
{
    for ($attempt = 1; $attempt -le 10; $attempt++)
    {
        try
        {
            $directory = [System.IO.Path]::GetDirectoryName($target)
            if (-not [System.IO.Directory]::Exists($directory)) { [void][System.IO.Directory]::CreateDirectory($directory) }
            if ([System.IO.File]::Exists($target)) { [System.IO.File]::SetAttributes($target, [System.IO.FileAttributes]::Normal) }
            [System.IO.File]::Copy($source, $target, $true)
            return $true
        }
        catch
        {
            if ($attempt -eq 10)
            {
                Write-UpdateLog ('Unable to copy ' + $target + ': ' + $_.Exception.Message)
                return $false
            }

            # the file may be still locked for a while after the application exits
            Wait-Responsive 1000
        }
    }
}

# Returns number of files, which could not be copied.
function Copy-UpdateFiles
{
    $root = $sourceDirectory.TrimEnd('\')
    $files = [System.IO.Directory]::GetFiles($root, '*', [System.IO.SearchOption]::AllDirectories)
    Write-UpdateLog ('Copying ' + $files.Length + ' files to ' + $targetDirectory)
    $failed = 0
    for ($index = 0; $index -lt $files.Length; $index++)
    {
        $source = $files[$index]
        $percent = [int][Math]::Floor(($index * 100) / $files.Length)
        Set-UpdateProgress ($textCopying -f ($index + 1), $files.Length) $percent

        if ($preservedFiles -contains [System.IO.Path]::GetFileName($source)) { continue }

        $target = [System.IO.Path]::Combine($targetDirectory, $source.Substring($root.Length + 1))
        if (-not (Copy-UpdateFile $source $target)) { $failed++ }
    }

    Set-UpdateProgress $null 100
    return $failed
}

# Returns the msiexec exit code.
function Install-Msi
{
    Set-UpdateProgress $textInstalling -1
    $startInfo = New-Object System.Diagnostics.ProcessStartInfo('msiexec.exe', $msiArguments)
    $startInfo.UseShellExecute = $false
    $process = [System.Diagnostics.Process]::Start($startInfo)
    while (-not $process.HasExited) { Wait-Responsive 200 }
    $exitCode = $process.ExitCode
    Write-UpdateLog ('msiexec exit code ' + $exitCode)
    return $exitCode
}

function Start-FallbackScript
{
    # comma has higher priority than plus, the arguments have to be prepared before
    $arguments = '/c ""' + $fallbackScript + '""'
    $startInfo = New-Object System.Diagnostics.ProcessStartInfo('cmd.exe', $arguments)
    $startInfo.UseShellExecute = $false
    $startInfo.CreateNoWindow = $true
    $startInfo.WorkingDirectory = [System.IO.Path]::GetDirectoryName($fallbackScript)
    $process = [System.Diagnostics.Process]::Start($startInfo)
    $process.WaitForExit()
}

$startTerminals = $true
try
{
    Write-UpdateLog ('Terminals update with progress started, mode ' + $updateMode)
    Show-ProgressWindow
    Set-UpdateProgress $textWaiting -1

    if (Wait-TerminalsExit)
    {
        if ($script:form -ne $null) { $script:form.Activate() }

        if ($updateMode -eq 'Msi')
        {
            $exitCode = Install-Msi
            # 1602 = canceled by the user, 3010 = success, restart required
            if ($exitCode -ne 0 -and $exitCode -ne 3010 -and $exitCode -ne 1602)
            {
                Show-UpdateFailure ($textInstallFailed -f $exitCode, $logFile)
            }
        }
        else
        {
            $failed = Copy-UpdateFiles
            Write-UpdateLog ('Copy finished, failed files: ' + $failed)
            if ($failed -gt 0)
            {
                Show-UpdateFailure ($textCopyFailed -f $failed, $logFile)
            }
        }
    }
    else
    {
        Write-UpdateLog 'Timeout waiting for Terminals to exit'
        $startTerminals = $false
    }
}
catch
{
    Write-UpdateLog ('Update with progress failed, running the script without progress: ' + $_.Exception.ToString())
    Close-ProgressWindow
    # the fallback script also starts Terminals
    $startTerminals = $false
    Start-FallbackScript
}

if ($startTerminals)
{
    Set-UpdateProgress $textStarting 100
    try
    {
        $startInfo = New-Object System.Diagnostics.ProcessStartInfo($terminalsExe)
        $startInfo.WorkingDirectory = $targetDirectory
        [void][System.Diagnostics.Process]::Start($startInfo)
        Write-UpdateLog 'Terminals started'
    }
    catch
    {
        Write-UpdateLog ('Unable to start Terminals: ' + $_.Exception.Message)
    }

    Wait-Responsive 1500
}

Close-ProgressWindow
